invoker.name.1 = Seed cache
invoker.goals.1 = clean package -Pnative ${develocity-options} --log-file ./01-prepare-cache.log -Dorg.slf4j.simpleLogger.log.com.gradle=debug -Dorg.slf4j.simpleLogger.log.develocity.goal.cache=debug

invoker.name.2 = Hit cache
invoker.goals.2 = clean package -Pnative ${develocity-options} --log-file ./02-hit-cache.log -Dorg.slf4j.simpleLogger.log.com.gradle=debug -Dorg.slf4j.simpleLogger.log.develocity.goal.cache=debug
